export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    CREATE_POST_REQUEST: 'USERS_CREATE_POST_REQUEST',
    CREATE_POST_SUCCESS: 'USERS_CREATE_POST_SUCCESS',
    CREATE_POST_FAILURE: 'USERS_CREATE_POST_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    GETPOSTPAGE: 'USERS_GETPOSTPAGE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE'    
};